name: tests

on:
  pull_request:
  push:
    tags:
      - "**"
  workflow_dispatch:

jobs:
  build_wheels:
    name: "Build ${{ matrix.CIBW_BUILD }} wheels on ${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        CIBW_BUILD: ["*"]
        exclude:
          - os: ubuntu-latest
            CIBW_BUILD: "*"
        include:
          - os: ubuntu-latest
            CIBW_BUILD: "*manylinux*"
          # Disable musllinux
          # - os: ubuntu-latest
          #   CIBW_BUILD: "*musllinux*"
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build ${{ matrix.CIBW_BUILD }} wheels on ${{ matrix.os }}
        uses: pypa/cibuildwheel@v2.10.2
        env:
          CIBW_BUILD: ${{ matrix.CIBW_BUILD }}

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: distribution
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Install build dependencies
        run: pip install build

      - name: Build source package
        run: python -m build --sdist .
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Test with tox
        run: tox --installpkg dist/*.tar.gz
      - name: Upload source package
        uses: actions/upload-artifact@v3
        with:
          name: distribution
          path: dist/

  check: # This job does nothing and is only used for the branch protection
    if: always()

    needs:
      - build_wheels
      - build_sdist

    runs-on: ubuntu-latest

    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}

  release:
    needs:
      - check
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: distribution
          path: dist/
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Install tox
        run: |
          python -m pip install tox
      - name: Release
        run: tox -e release
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
